DROP TABLE c_test;
CREATE EXTERNAL TABLE c_test (
  Address string,
  Larceny int,
  Robbery int,
  Vehicle int
) ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",",
"quoteChar" = '"',
"escapeChar" = '\\'
)
STORED AS TEXTFILE
LOCATION '/user/w205/crimetest1';

DROP TABLE C_RANK;
CREATE TABLE C_RANK AS
SELECT Address,
RANK() OVER (ORDER BY LARCENY DESC) AS LARC_RANK,
RANK() OVER (ORDER BY ROBBERY DESC) AS ROBB_RANK,
RANK() OVER (ORDER BY VEHICLE DESC) AS VEH_RANK
FROM C_TEST;

DROP TABLE C_AVG;
CREATE TABLE C_AVG AS
SELECT Address,
(LARC_RANK + ROBB_RANK + VEH_RANK)/3 AS AVG_RANK
FROM C_RANK;

DROP TABLE C_SCORE;
CREATE TABLE C_SCORE AS
SELECT Address,
AVG_RANK*10/(MAX(AVG_RANK) OVER ()) AS SCORE
FROM C_AVG;
