DROP TABLE crime_table;
CREATE EXTERNAL TABLE crime_table (
  IncidntNum int,
  Category string,
  Descript string,
  DayOfWeek string,
  Date date,
  Time int,
  PdDistrict string,
  Resolution string,
  Address string,
  Y int,
  X int,
  Location string,
  PdId int
) ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ( "separatorChar" = ",",
"quoteChar" = '"',
"escapeChar" = '\\'
)
STORED AS TEXTFILE
LOCATION '/user/w205/crimenew';


DROP TABLE COUNT_CRIME;
CREATE TABLE COUNT_CRIME AS
SELECT CATEGORY, COUNT(CATEGORY) AS CT_CAT FROM CRIME_TABLE
GROUP BY CATEGORY
ORDER BY CT_CAT DESC;

SELECT * FROM COUNT_CRIME;


DROP TABLE COUNT_DES_CRIME;
CREATE TABLE COUNT_DES_CRIME AS
SELECT DESCRIPT, COUNT(DESCRIPT) AS CT_DESCR FROM CRIME_TABLE
GROUP BY DESCRIPT
ORDER BY CT_DESCR DESC;

SELECT * FROM COUNT_DES_CRIME;

DROP TABLE BIKE_DATE;
CREATE TABLE BIKE_DATE AS
SELECT DATE FROM CRIME_TABLE WHERE DESCRIPT = 'GRAND THEFT BICYCLE'
;

SELECT * FROM BIKE_DATE;

DROP TABLE PET_BIKE_DATE;
CREATE TABLE PET_BIKE_DATE AS
SELECT DATE FROM CRIME_TABLE WHERE DESCRIPT = 'PETTY THEFT BICYCLE'
;

SELECT * FROM PET_BIKE_DATE;


DROP TABLE BIKE_THEFT;
CREATE TABLE BIKE_THEFT AS
SELECT * FROM CRIME_TABLE
WHERE DESCRIPT = 'GRAND THEFT BICYCLE' OR DESCRIPT = 'PETTY THEFT BICYCLE'
;

DROP TABLE BIKE_LOC;
CREATE TABLE BIKE_LOC AS
SELECT PDDISTRICT, COUNT(PDDISTRICT) AS CT_PDDIST FROM BIKE_THEFT
GROUP BY PDDISTRICT
ORDER BY CT_PDDIST DESC;

DROP TABLE BIKE_DATE;
CREATE TABLE BIKE_DATE AS
SELECT DATE, COUNT(DATE) AS CT_DATE FROM BIKE_THEFT
GROUP BY DATE
ORDER BY CT_DATE DESC;


DROP TABLE BIKE_DATE;
CREATE TABLE BIKE_DATE AS
SELECT DATE, COUNT(DATE) AS CT_DATE FROM BIKE_THEFT
GROUP BY DATE
ORDER BY DATE DESC;

DROP TABLE BIKE_DAY;
CREATE TABLE BIKE_DAY AS
SELECT DAYOFWEEK, COUNT(DAYOFWEEK) AS CT_DAY FROM BIKE_THEFT
GROUP BY DAYOFWEEK
ORDER BY CT_DAY;

----------------------------------------------------------------

DROP TABLE PD_BIKE_DATE;
CREATE TABLE PD_BIKE_DATE AS
SELECT DATE, COUNT(DATE) AS CT_DATE FROM BIKE_THEFT WHERE PDDISTRICT = 'SOUTHERN'
GROUP BY DATE
ORDER BY CT_DATE;

DROP TABLE PD_BIKE_MISS;
CREATE TABLE PD_BIKE_MISS AS
SELECT DATE, COUNT(DATE) AS CT_DATE FROM BIKE_THEFT WHERE PDDISTRICT = 'MISSION'
GROUP BY DATE
ORDER BY CT_DATE;

DROP TABLE PD_BIKE_CEN;
CREATE TABLE PD_BIKE_CEN AS
SELECT DATE, COUNT(DATE) AS CT_DATE FROM BIKE_THEFT WHERE PDDISTRICT = 'CENTRAL'
GROUP BY DATE
ORDER BY CT_DATE;


DROP TABLE PD_BIKE_NOR;
CREATE TABLE PD_BIKE_NOR AS
SELECT DATE, COUNT(DATE) AS CT_DATE FROM BIKE_THEFT WHERE PDDISTRICT = 'NORTHERN'
GROUP BY DATE
ORDER BY CT_DATE;

DROP TABLE PD_BIKE_PAR;
CREATE TABLE PD_BIKE_PAR AS
SELECT DATE, COUNT(DATE) AS CT_DATE FROM BIKE_THEFT WHERE PDDISTRICT = 'PARK'
GROUP BY DATE
ORDER BY CT_DATE;

DROP TABLE PD_BIKE_RICH;
CREATE TABLE PD_BIKE_RICH AS
SELECT DATE, COUNT(DATE) AS CT_DATE FROM BIKE_THEFT WHERE PDDISTRICT = 'RICHMOND'
GROUP BY DATE
ORDER BY CT_DATE;

DROP TABLE PD_BIKE_TAR;
CREATE TABLE PD_BIKE_TAR AS
SELECT DATE, COUNT(DATE) AS CT_DATE FROM BIKE_THEFT WHERE PDDISTRICT = 'TARAVAL'
GROUP BY DATE
ORDER BY CT_DATE;

DROP TABLE PD_BIKE_TEN;
CREATE TABLE PD_BIKE_TEN AS
SELECT DATE, COUNT(DATE) AS CT_DATE FROM BIKE_THEFT WHERE PDDISTRICT = 'TENDERLOIN'
GROUP BY DATE
ORDER BY CT_DATE;

DROP TABLE PD_BIKE_ING;
CREATE TABLE PD_BIKE_ING AS
SELECT DATE, COUNT(DATE) AS CT_DATE FROM BIKE_THEFT WHERE PDDISTRICT = 'INGLESIDE'
GROUP BY DATE
ORDER BY CT_DATE;

DROP TABLE PD_BIKE_BAY;
CREATE TABLE PD_BIKE_BAY AS
SELECT DATE, COUNT(DATE) AS CT_DATE FROM BIKE_THEFT WHERE PDDISTRICT = 'BAYVIEW'
GROUP BY DATE
ORDER BY CT_DATE;
---------------------------------------------------------------------------------

DROP TABLE AUTO_OFFENSE;
CREATE TABLE AUTO_OFFENSE AS
SELECT * FROM CRIME_TABLE
WHERE DESCRIPT = 'GRAND THEFT FROM LOCKED AUTO' OR DESCRIPT = 'STOLEN AUTOMOBILE'
OR DESCRIPT = 'PETTY THEFT FROM LOCKED AUTO' OR DESCRIPT = 'MALICIOUS MISCHIEF, VANDALISM OF VEHICLES'
OR DESCRIPT = 'STOLEN TRUCK' OR DESCRIPT = 'GRAND THEFT FROM UNLOCKED AUTO' OR
DESCRIPT = 'PETTY THEFT FROM UNLOCKED AUTO'
;

DROP TABLE AUTO_LOC;
CREATE TABLE AUTO_LOC AS
SELECT PDDISTRICT, COUNT(PDDISTRICT) AS CT_PDDIST FROM AUTO_OFFENSE
GROUP BY PDDISTRICT
ORDER BY CT_PDDIST DESC;


DROP TABLE AUTO_DAY;
CREATE TABLE AUTO_DAY AS
SELECT DAYOFWEEK, COUNT(DAYOFWEEK) AS CT_DAY FROM AUTO_OFFENSE
GROUP BY DAYOFWEEK
ORDER BY CT_DAY;

DROP TABLE AUTO_DATE;
CREATE TABLE AUTO_DATE AS
SELECT DATE, COUNT(DATE) AS CT_DATE FROM AUTO_OFFENSE
GROUP BY DATE
ORDER BY DATE DESC;

DROP TABLE PD_AUTO_STH;
CREATE TABLE PD_AUTO_STH AS
SELECT DATE, COUNT(DATE) AS CT_DATE FROM AUTO_OFFENSE WHERE PDDISTRICT = 'SOUTHERN'
GROUP BY DATE
ORDER BY CT_DATE;

DROP TABLE PD_AUTO_MISS;
CREATE TABLE PD_AUTO_MISS AS
SELECT DATE, COUNT(DATE) AS CT_DATE FROM AUTO_OFFENSE WHERE PDDISTRICT = 'MISSION'
GROUP BY DATE
ORDER BY CT_DATE;

DROP TABLE PD_AUTO_CEN;
CREATE TABLE PD_AUTO_CEN AS
SELECT DATE, COUNT(DATE) AS CT_DATE FROM AUTO_OFFENSE WHERE PDDISTRICT = 'CENTRAL'
GROUP BY DATE
ORDER BY CT_DATE;

DROP TABLE PD_AUTO_NOR;
CREATE TABLE PD_AUTO_NOR AS
SELECT DATE, COUNT(DATE) AS CT_DATE FROM AUTO_OFFENSE WHERE PDDISTRICT = 'NORTHERN'
GROUP BY DATE
ORDER BY CT_DATE;

DROP TABLE PD_AUTO_PAR;
CREATE TABLE PD_AUTO_PAR AS
SELECT DATE, COUNT(DATE) AS CT_DATE FROM AUTO_OFFENSE WHERE PDDISTRICT = 'PARK'
GROUP BY DATE
ORDER BY CT_DATE;

DROP TABLE PD_AUTO_RICH;
CREATE TABLE PD_AUTO_RICH AS
SELECT DATE, COUNT(DATE) AS CT_DATE FROM AUTO_OFFENSE WHERE PDDISTRICT = 'RICHMOND'
GROUP BY DATE
ORDER BY CT_DATE;

DROP TABLE PD_AUTO_TAR;
CREATE TABLE PD_AUTO_TAR AS
SELECT DATE, COUNT(DATE) AS CT_DATE FROM AUTO_OFFENSE WHERE PDDISTRICT = 'TARAVAL'
GROUP BY DATE
ORDER BY CT_DATE;

DROP TABLE PD_AUTO_TEN;
CREATE TABLE PD_AUTO_TEN AS
SELECT DATE, COUNT(DATE) AS CT_DATE FROM AUTO_OFFENSE WHERE PDDISTRICT = 'TENDERLOIN'
GROUP BY DATE
ORDER BY CT_DATE;

DROP TABLE PD_AUTO_ING;
CREATE TABLE PD_AUTO_ING AS
SELECT DATE, COUNT(DATE) AS CT_DATE FROM AUTO_OFFENSE WHERE PDDISTRICT = 'INGLESIDE'
GROUP BY DATE
ORDER BY CT_DATE;

DROP TABLE PD_AUTO_BAY;
CREATE TABLE PD_AUTO_BAY AS
SELECT DATE, COUNT(DATE) AS CT_DATE FROM AUTO_OFFENSE WHERE PDDISTRICT = 'BAYVIEW'
GROUP BY DATE
ORDER BY CT_DATE;
